"""Knowledge domain public facade.

Re-exports the domain services split by concern into ``kb`` (knowledge base
CRUD + model resolution), ``documents`` (documents/attachments), and
``permissions`` (access control). Application and orchestration code imports
this module so the split stays an internal detail.
"""

from app.shareddomain.knowledge.documents import (
    DEFAULT_DOCUMENT_META,
    DOCUMENT_UPLOADED_STATUS,
    MAX_DOCUMENT_UPLOAD_BYTES,
    RESTRICTED_FILENAME_MARKERS,
    UPLOAD_CHUNK_BYTES,
    attachment_to_response,
    clean_upload_filename,
    create_knowledge_documents_from_attachments,
    delete_knowledge_attachment,
    document_to_response,
    knowledge_document_path,
    knowledge_object_storage,
    list_knowledge_documents,
    upload_knowledge_attachment,
)
from app.shareddomain.knowledge.kb import (
    ACTIVE_STATUS,
    ARCHIVED_STATUS,
    KNOWLEDGE_BASE_STATUSES,
    create_knowledge_base,
    delete_knowledge_base_permanently,
    get_default_knowledge_model,
    get_knowledge_base,
    get_knowledge_model,
    knowledge_base_to_response,
    list_knowledge_bases,
    require_can_manage_permissions,
    run_knowledge_model_test,
    test_knowledge_base_models,
    update_knowledge_base,
)
from app.shareddomain.knowledge.permissions import (
    RESOURCE_PERMISSIONS,
    RESOURCE_TYPE,
    effective_permission,
    get_user_grant,
    list_resource_permissions,
    require_knowledge_base_permission,
    revoke_resource_permission,
    upsert_resource_permission,
    validate_permission,
)

__all__ = [
    "ACTIVE_STATUS",
    "ARCHIVED_STATUS",
    "DEFAULT_DOCUMENT_META",
    "DOCUMENT_UPLOADED_STATUS",
    "KNOWLEDGE_BASE_STATUSES",
    "MAX_DOCUMENT_UPLOAD_BYTES",
    "RESOURCE_PERMISSIONS",
    "RESOURCE_TYPE",
    "RESTRICTED_FILENAME_MARKERS",
    "UPLOAD_CHUNK_BYTES",
    "attachment_to_response",
    "clean_upload_filename",
    "create_knowledge_base",
    "create_knowledge_documents_from_attachments",
    "delete_knowledge_attachment",
    "delete_knowledge_base_permanently",
    "document_to_response",
    "effective_permission",
    "get_default_knowledge_model",
    "get_knowledge_base",
    "get_knowledge_model",
    "get_user_grant",
    "knowledge_base_to_response",
    "knowledge_document_path",
    "knowledge_object_storage",
    "list_knowledge_bases",
    "list_knowledge_documents",
    "list_resource_permissions",
    "require_can_manage_permissions",
    "require_knowledge_base_permission",
    "revoke_resource_permission",
    "run_knowledge_model_test",
    "test_knowledge_base_models",
    "update_knowledge_base",
    "upload_knowledge_attachment",
    "upsert_resource_permission",
    "validate_permission",
]
