"""Agent use-case facade.

Public entry point for the agent API: CRUD use cases from the agents domain
plus run orchestration and tool construction split into
``app.application.agent_runs`` and ``app.application.agent_tools``.
"""

from app.application.agent_runs import (
    cancel_agent_run,
    create_agent_run,
    enqueue_prepared_agent_run,
    execution_messages,
    get_agent_run_entity,
    get_agent_run_response,
    list_agent_runs,
    list_agent_run_tool_calls,
    prepare_agent_run,
    regenerate_agent_run,
    resolve_agent_tool_approval,
    set_agent_run_feedback,
    stream_agent_run,
)
from app.application.agent_tools import (
    KnowledgeSearchInput,
    build_knowledge_search_tool,
    build_mcp_agent_tool,
    mcp_function_name,
    run_to_response,
    safe_agent_error,
)
from app.application.agent_access import (
    authenticate_agent_api_credential,
    create_agent_api_credential,
    create_external_agent_run,
    external_run_to_response,
    get_agent_monitoring,
    get_external_agent_run,
    get_public_agent_profile,
    get_published_agent_context,
    get_workspace_published_agent_context,
    list_agent_api_credentials,
    list_agent_conversation_users,
    list_agent_logs,
    list_external_agent_runs,
    list_external_agent_run_tool_calls,
    list_public_agent_conversations,
    revoke_agent_api_credential,
    rotate_agent_api_credential,
    resolve_external_agent_tool_approval,
    regenerate_external_agent_run,
    set_external_agent_run_feedback,
    stream_external_agent_run,
)
from app.application.workflow_uploads import (
    resolve_workspace_agent_files,
    upload_public_agent_files,
    upload_workspace_agent_files,
)
from app.shareddomain.agents.services import (
    ACTIVE_STATUS,
    accessible_agent_knowledge_bases,
    can_edit_agent,
    create_agent,
    delete_agent,
    get_agent,
    get_agent_model,
    get_agent_response,
    list_agents,
    update_agent,
)
from app.shareddomain.agents.permissions import (
    list_agent_permissions,
    require_agent_edit,
    revoke_agent_permission,
    upsert_agent_permission,
)

__all__ = [
    "ACTIVE_STATUS",
    "KnowledgeSearchInput",
    "accessible_agent_knowledge_bases",
    "authenticate_agent_api_credential",
    "build_knowledge_search_tool",
    "build_mcp_agent_tool",
    "can_edit_agent",
    "cancel_agent_run",
    "create_agent",
    "create_agent_api_credential",
    "create_agent_run",
    "create_external_agent_run",
    "delete_agent",
    "execution_messages",
    "enqueue_prepared_agent_run",
    "external_run_to_response",
    "get_agent",
    "get_agent_model",
    "get_agent_monitoring",
    "get_agent_response",
    "get_agent_run_response",
    "get_agent_run_entity",
    "get_external_agent_run",
    "get_public_agent_profile",
    "get_published_agent_context",
    "get_workspace_published_agent_context",
    "list_agent_runs",
    "list_agent_run_tool_calls",
    "list_agent_api_credentials",
    "list_agent_conversation_users",
    "list_agent_logs",
    "list_agent_permissions",
    "list_agents",
    "list_external_agent_runs",
    "list_external_agent_run_tool_calls",
    "list_public_agent_conversations",
    "mcp_function_name",
    "prepare_agent_run",
    "regenerate_agent_run",
    "require_agent_edit",
    "resolve_agent_tool_approval",
    "set_agent_run_feedback",
    "resolve_workspace_agent_files",
    "revoke_agent_api_credential",
    "revoke_agent_permission",
    "rotate_agent_api_credential",
    "resolve_external_agent_tool_approval",
    "regenerate_external_agent_run",
    "set_external_agent_run_feedback",
    "run_to_response",
    "safe_agent_error",
    "stream_agent_run",
    "stream_external_agent_run",
    "upload_public_agent_files",
    "upload_workspace_agent_files",
    "update_agent",
    "upsert_agent_permission",
]
