from typing import Any


CATALOG_VERIFIED_AT = "2026-09-10"


def integration(
    *,
    adapter: str,
    runtime_sdk: str,
    provider_sdk: str | None,
    api_protocol: str,
    model_catalog: str,
    docs_url: str,
    models_url: str | None = None,
) -> dict[str, Any]:
    return {
        "adapter": adapter,
        "runtime_sdk": runtime_sdk,
        "provider_sdk": provider_sdk,
        "api_protocol": api_protocol,
        "model_catalog": model_catalog,
        "docs_url": docs_url,
        "models_url": models_url or docs_url,
        "verified_at": CATALOG_VERIFIED_AT,
    }


PROVIDER_INTEGRATIONS = {
    "aliyun_bai_lian_model_provider": integration(
        adapter="langchain-openai",
        runtime_sdk="openai",
        provider_sdk="dashscope",
        api_protocol="openai_chat_completions",
        model_catalog="static_recommendations",
        docs_url="https://help.aliyun.com/zh/model-studio/developer-reference/use-qwen-by-calling-api",
        models_url="https://help.aliyun.com/zh/model-studio/models",
    ),
    "model_anthropic_provider": integration(
        adapter="langchain-anthropic",
        runtime_sdk="anthropic",
        provider_sdk="anthropic",
        api_protocol="anthropic_messages",
        model_catalog="static_recommendations",
        docs_url="https://platform.claude.com/docs/en/api/client-sdks",
        models_url="https://platform.claude.com/docs/en/models/overview",
    ),
    "model_aws_bedrock_provider": integration(
        adapter="langchain-aws",
        runtime_sdk="boto3",
        provider_sdk="boto3",
        api_protocol="aws_bedrock_converse",
        model_catalog="account_or_region",
        docs_url="https://docs.aws.amazon.com/bedrock/latest/userguide/getting-started-api-ex-python.html",
        models_url="https://docs.aws.amazon.com/bedrock/latest/userguide/model-cards.html",
    ),
    "model_azure_provider": integration(
        adapter="langchain-openai",
        runtime_sdk="openai",
        provider_sdk="openai",
        api_protocol="azure_openai",
        model_catalog="deployment_defined",
        docs_url="https://learn.microsoft.com/en-us/azure/ai-foundry/openai/how-to/switching-endpoints",
        models_url="https://learn.microsoft.com/en-us/azure/foundry/foundry-models/concepts/models-sold-directly-by-azure?pivots=azure-openai",
    ),
    "model_custom_provider": integration(
        adapter="langchain-openai",
        runtime_sdk="openai",
        provider_sdk=None,
        api_protocol="openai_compatible",
        model_catalog="user_defined",
        docs_url="https://platform.openai.com/docs/api-reference/chat",
    ),
    "model_deepseek_provider": integration(
        adapter="langchain-deepseek",
        runtime_sdk="openai",
        provider_sdk=None,
        api_protocol="openai_chat_completions",
        model_catalog="static_recommendations",
        docs_url="https://api-docs.deepseek.com/",
        models_url="https://api-docs.deepseek.com/quick_start/pricing/",
    ),
    "model_docker_ai_provider": integration(
        adapter="langchain-openai",
        runtime_sdk="openai",
        provider_sdk=None,
        api_protocol="openai_compatible",
        model_catalog="runtime_discovered",
        docs_url="https://docs.docker.com/ai/model-runner/api-reference/",
        models_url="https://hub.docker.com/u/ai",
    ),
    "model_gemini_provider": integration(
        adapter="langchain-google-genai",
        runtime_sdk="google-genai",
        provider_sdk="google-genai",
        api_protocol="google_genai",
        model_catalog="static_recommendations",
        docs_url="https://ai.google.dev/gemini-api/docs/libraries",
        models_url="https://ai.google.dev/gemini-api/docs/models",
    ),
    "model_kimi_provider": integration(
        adapter="langchain-openai",
        runtime_sdk="openai",
        provider_sdk=None,
        api_protocol="openai_chat_completions",
        model_catalog="static_recommendations",
        docs_url="https://platform.kimi.com/docs/api/chat",
        models_url="https://platform.kimi.com/docs/guide/models-overview",
    ),
    "model_local_provider": integration(
        adapter="langchain-openai",
        runtime_sdk="openai",
        provider_sdk=None,
        api_protocol="openai_compatible",
        model_catalog="runtime_discovered",
        docs_url="https://platform.openai.com/docs/api-reference/chat",
    ),
    "model_ollama_provider": integration(
        adapter="langchain-ollama",
        runtime_sdk="ollama",
        provider_sdk="ollama",
        api_protocol="ollama",
        model_catalog="runtime_discovered",
        docs_url="https://docs.ollama.com/api/introduction",
        models_url="https://ollama.com/library",
    ),
    "model_openai_provider": integration(
        adapter="langchain-openai",
        runtime_sdk="openai",
        provider_sdk="openai",
        api_protocol="openai_chat_completions",
        model_catalog="static_recommendations",
        docs_url="https://developers.openai.com/api/docs/libraries",
        models_url="https://developers.openai.com/api/docs/models",
    ),
    "model_regolo_provider": integration(
        adapter="langchain-openai",
        runtime_sdk="openai",
        provider_sdk="regolo",
        api_protocol="openai_chat_completions",
        model_catalog="runtime_discovered",
        docs_url="https://docs.regolo.ai/getting-started/first-api-call/",
        models_url="https://docs.regolo.ai/models/catalog/",
    ),
    "model_siliconflow_provider": integration(
        adapter="langchain-openai",
        runtime_sdk="openai",
        provider_sdk=None,
        api_protocol="openai_chat_completions",
        model_catalog="static_recommendations",
        docs_url="https://docs.siliconflow.cn/docs/api/chat-completions-post",
        models_url="https://cloud.siliconflow.cn/models",
    ),
    "model_tencent_cloud_provider": integration(
        adapter="langchain-openai",
        runtime_sdk="openai",
        provider_sdk=None,
        api_protocol="openai_chat_completions",
        model_catalog="static_recommendations",
        docs_url="https://cloud.tencent.com/document/product/1823/130079",
        models_url="https://cloud.tencent.com/document/product/1823/130051",
    ),
    "model_tencent_provider": integration(
        adapter="langchain-openai",
        runtime_sdk="openai",
        provider_sdk="tencentcloud-sdk-python-hunyuan",
        api_protocol="openai_chat_completions",
        model_catalog="static_recommendations",
        docs_url="https://cloud.tencent.com/document/product/1729/111007",
        models_url="https://cloud.tencent.com/document/product/1729/104753",
    ),
    "model_vllm_provider": integration(
        adapter="langchain-openai",
        runtime_sdk="openai",
        provider_sdk="vllm",
        api_protocol="openai_compatible",
        model_catalog="runtime_discovered",
        docs_url="https://docs.vllm.ai/en/latest/serving/openai_compatible_server/",
    ),
    "model_volcanic_engine_provider": integration(
        adapter="langchain-openai",
        runtime_sdk="openai",
        provider_sdk="volcengine-python-sdk",
        api_protocol="openai_chat_completions",
        model_catalog="account_or_region",
        docs_url="https://www.volcengine.com/docs/82379/1330626",
        models_url="https://www.volcengine.com/docs/82379/1330310",
    ),
    "model_wenxin_provider": integration(
        adapter="langchain-openai",
        runtime_sdk="openai",
        provider_sdk="qianfan",
        api_protocol="openai_chat_completions",
        model_catalog="static_recommendations",
        docs_url="https://ai.baidu.com/ai-doc/WENXINWORKSHOP/1m9ra0mle",
        models_url="https://cloud.baidu.com/doc/qianfan/s/wmh4sv6ya",
    ),
    "model_xf_provider": integration(
        adapter="langchain-openai",
        runtime_sdk="openai",
        provider_sdk=None,
        api_protocol="openai_chat_completions",
        model_catalog="static_recommendations",
        docs_url="https://www.xfyun.cn/doc/spark/HTTP%E8%B0%83%E7%94%A8%E6%96%87%E6%A1%A3.html",
    ),
    "model_xinference_provider": integration(
        adapter="langchain-openai",
        runtime_sdk="openai",
        provider_sdk="xinference-client",
        api_protocol="openai_compatible",
        model_catalog="runtime_discovered",
        docs_url="https://inference.readthedocs.io/en/latest/user_guide/client_api.html",
    ),
    "model_zhipu_provider": integration(
        adapter="langchain-openai",
        runtime_sdk="openai",
        provider_sdk="zhipuai",
        api_protocol="openai_chat_completions",
        model_catalog="static_recommendations",
        docs_url="https://docs.bigmodel.cn/cn/guide/develop/openai/introduction",
        models_url="https://docs.bigmodel.cn/cn/guide/models/text/glm-5",
    ),
}


__all__ = ["CATALOG_VERIFIED_AT", "PROVIDER_INTEGRATIONS"]
