/* @jsxImportSource react */
import { describe, expect, test } from "bun:test"

import { translate, type Language, type TFunction } from "../src/i18n"
import {
  toolDisplayDescription,
  toolDisplayName,
  toolSourceDisplayName,
  withArtifactDownloadLinks,
  withArtifactDownloadLinksInContent,
} from "../src/lib/tool-display"

const t = ((key: string) => key) as TFunction
const translated = (language: Language) =>
  ((key, values) => translate(language, key, values)) as TFunction

describe("tool display helpers", () => {
  test("localizes built-in tool display names", () => {
    expect(
      toolDisplayName(
        {
          function_name: "inline_python",
          display_name: "Python",
          description: "Runs code",
        },
        t
      )
    ).toBe("Python 代码")
    expect(
      toolDisplayName(
        {
          function_name: "current_time",
          display_name: "Time",
          description: "UTC time",
        },
        t
      )
    ).toBe("当前时间")
    expect(
      toolDisplayName(
        {
          function_name: "create_artifact",
          display_name: "Create document or page",
          description: "Creates a file",
        },
        t
      )
    ).toBe("创建文件")
  })

  test("falls back to the configured display name for custom tools", () => {
    expect(
      toolDisplayName(
        {
          function_name: "search_web",
          display_name: "Web Search",
          description: "Searches the web",
        },
        t
      )
    ).toBe("Web Search")
  })

  test("localizes built-in tool display descriptions", () => {
    expect(
      toolDisplayDescription(
        {
          function_name: "inline_python",
          display_name: "Python",
          description: "Runs code",
        },
        t
      )
    ).toBe("在工作流沙箱中运行 Python 代码。")
    expect(
      toolDisplayDescription(
        {
          function_name: "current_time",
          display_name: "Time",
          description: "UTC time",
        },
        t
      )
    ).toBe("返回当前 UTC 时间。")
    expect(
      toolDisplayDescription(
        {
          function_name: "create_artifact",
          display_name: "Create document or page",
          description: "Creates a file",
        },
        t
      )
    ).toBe(
      "根据文件名和内容创建可下载文件；文本文件直接保存，复杂格式由平台生成。"
    )
  })

  test("translates the artifact tool in all supported languages", () => {
    const tool = {
      function_name: "create_artifact",
      display_name: "Create document or page",
      description: "Creates a file",
    }

    expect(toolDisplayName(tool, translated("zh-Hans"))).toBe("创建文件")
    expect(toolDisplayName(tool, translated("zh-Hant"))).toBe("建立檔案")
    expect(toolDisplayName(tool, translated("en"))).toBe("Create file")
    expect(toolDisplayDescription(tool, translated("zh-Hant"))).toBe(
      "根據檔名和內容建立可下載檔案；文字檔案直接儲存，複雜格式由平台產生。"
    )
    expect(toolDisplayDescription(tool, translated("en"))).toBe(
      "Create a downloadable file from its name and content; text files are saved directly and complex formats are generated by the platform."
    )
  })

  test("falls back to the configured description for custom tools", () => {
    expect(
      toolDisplayDescription(
        {
          function_name: "search_web",
          display_name: "Web Search",
          description: "Searches the web",
        },
        t
      )
    ).toBe("Searches the web")
  })

  test("localizes built-in tool sources", () => {
    expect(
      toolSourceDisplayName({ kind: "builtin", name: "Builtin" }, t)
    ).toBe("内置")
  })

  test("falls back to the source name for external sources", () => {
    expect(
      toolSourceDisplayName({ kind: "mcp", name: "Search MCP" }, t)
    ).toBe("Search MCP")
  })

  test("normalizes absolute artifact URLs and keeps the latest file version", () => {
    const oldUrl = "/api/v1/artifacts/old-token"
    const latestUrl = "/api/v1/artifacts/latest-token"
    const value = withArtifactDownloadLinks(
      `下载：https://chat.kimi.com${latestUrl}`,
      [
        {
          tool_name: "create_artifact",
          status: "succeeded",
          output: { filename: "论文.docx", download_url: oldUrl },
        },
        {
          tool_name: "create_artifact",
          status: "succeeded",
          output: { filename: "论文.docx", download_url: latestUrl },
        },
      ]
    )

    expect(value).toBe(`下载：[论文.docx](${latestUrl})`)
    expect(value).not.toContain("chat.kimi.com")
    expect(value).not.toContain(oldUrl)
  })

  test("replaces a copied artifact token with the verified filename link", () => {
    const validUrl = "/api/v1/artifacts/valid-token"
    const copiedUrl = "/api/v1/artifacts/copied-token"
    const value = withArtifactDownloadLinks(
      `下载链接：[${copiedUrl}](${copiedUrl})`,
      [
        {
          tool_name: "create_artifact",
          status: "succeeded",
          output: { filename: "verify_stream.py", download_url: validUrl },
        },
      ]
    )

    expect(value).toBe(`下载链接：[verify_stream.py](${validUrl})`)
    expect(value).not.toContain(copiedUrl)
  })

  test("normalizes raw artifact URLs in log content", () => {
    const url = "/api/v1/artifacts/production-token"
    const value = withArtifactDownloadLinksInContent(
      `文件名：校外培训行政处罚相关条例汇编.docx\n下载链接：${url}`
    )

    expect(value).toContain(`[校外培训行政处罚相关条例汇编.docx](${url})`)
    expect(value).not.toContain(`下载链接：${url}`)
  })

  test("normalizes links split by whitespace and ignores unmentioned artifacts", () => {
    const url = "/api/v1/artifacts/document-token"
    const tempUrl = "/api/v1/artifacts/test-token"
    const value = withArtifactDownloadLinks(
      `文件名：规章制度（通用模板）.docx\n下载：[规章制度（通用模板）.docx]\n(${url})`,
      [
        {
          tool_name: "create_artifact",
          status: "succeeded",
          output: { filename: "规章制度（通用模板）.docx", download_url: url },
        },
        {
          tool_name: "create_artifact",
          status: "succeeded",
          output: { filename: "test_docx.py", download_url: tempUrl },
        },
      ]
    )

    expect(value).toContain(`[规章制度（通用模板）.docx](${url})`)
    expect(value).not.toContain(tempUrl)
    expect(value).not.toContain("test_docx.py")
  })
})
