/* @jsxImportSource react */
import { describe, expect, test } from "bun:test"

import { translate, type Language, type TFunction } from "../src/i18n"
import {
  toolDisplayDescription,
  toolDisplayName,
  toolSourceDisplayName,
  withArtifactDownloadLinks,
  withArtifactDownloadLinksInContent,
} from "../src/lib/tool-display"

const t = ((key: string) => key) as TFunction
const translated = (language: Language) =>
  ((key, values) => translate(language, key, values)) as TFunction

describe("tool display helpers", () => {
  test("localizes built-in tool display names", () => {
    expect(
      toolDisplayName(
        {
          function_name: "inline_python",
          display_name: "Python",
          description: "Runs code",
        },
        t
      )
    ).toBe("Python 代码")
    expect(
      toolDisplayName(
        {
          function_name: "current_time",
          display_name: "Time",
          description: "UTC time",
        },
        t
      )
    ).toBe("当前时间")
    expect(
      toolDisplayName(
        {
          function_name: "create_artifact",
          display_name: "Create document or page",
          description: "Creates a file",
        },
        t
      )
    ).toBe("创建文件")
    expect(
      toolDisplayName(
        {
          function_name: "documents_skill",
          display_name: "Documents Skill",
          description: "Creates DOCX files",
        },
        t
      )
    ).toBe("DOCX")
    expect(
      toolDisplayName(
        {
          function_name: "pptx_skill",
          display_name: "PPTX Skill",
          description: "Creates PPTX decks",
        },
        t
      )
    ).toBe("PPTX")
    expect(
      toolDisplayName(
        {
          function_name: "pdf_skill",
          display_name: "PDF Skill",
          description: "Creates PDFs",
        },
        t
      )
    ).toBe("PDF")
    expect(
      toolDisplayName(
        {
          function_name: "spreadsheets_skill",
          display_name: "Spreadsheets Skill",
          description: "Creates workbooks",
        },
        t
      )
    ).toBe("Excel")
    expect(
      toolDisplayName(
        {
          function_name: "generate_image",
          display_name: "Generate image",
          description: "Creates an image",
        },
        t
      )
    ).toBe("图片生成")
  })

  test("falls back to the configured display name for custom tools", () => {
    expect(
      toolDisplayName(
        {
          function_name: "search_web",
          display_name: "Web Search",
          description: "Searches the web",
        },
        t
      )
    ).toBe("Web Search")
  })

  test("localizes built-in tool display descriptions", () => {
    expect(
      toolDisplayDescription(
        {
          function_name: "inline_python",
          display_name: "Python",
          description: "Runs code",
        },
        t
      )
    ).toBe("在工作流沙箱中运行 Python 代码。")
    expect(
      toolDisplayDescription(
        {
          function_name: "current_time",
          display_name: "Time",
          description: "UTC time",
        },
        t
      )
    ).toBe("返回当前时间。")
    expect(
      toolDisplayDescription(
        {
          function_name: "create_artifact",
          display_name: "Create document or page",
          description: "Creates a file",
        },
        t
      )
    ).toBe(
      "根据文件名和内容创建可下载文件；文本文件直接保存，复杂格式由平台生成。"
    )
    expect(
      toolDisplayDescription(
        {
          function_name: "pdf_skill",
          display_name: "PDF Skill",
          description: "Creates PDFs",
        },
        t
      )
    ).toBe("创建 PDF 文件。")
    expect(
      toolDisplayDescription(
        {
          function_name: "pptx_skill",
          display_name: "PPTX Skill",
          description: "Creates PPTX decks",
        },
        t
      )
    ).toBe("创建 PPTX 演示文稿。")
  })

  test("translates the artifact tool in all supported languages", () => {
    const tool = {
      function_name: "create_artifact",
      display_name: "Create document or page",
      description: "Creates a file",
    }

    expect(toolDisplayName(tool, translated("zh-Hans"))).toBe("创建文件")
    expect(toolDisplayName(tool, translated("zh-Hant"))).toBe("建立檔案")
    expect(toolDisplayName(tool, translated("en"))).toBe("Create file")
    expect(toolDisplayDescription(tool, translated("zh-Hant"))).toBe(
      "根據檔名和內容建立可下載檔案；文字檔案直接儲存，複雜格式由平台產生。"
    )
    expect(toolDisplayDescription(tool, translated("en"))).toBe(
      "Create a downloadable file from its name and content; text files are saved directly and complex formats are generated by the platform."
    )
  })

  test("falls back to the configured description for custom tools", () => {
    expect(
      toolDisplayDescription(
        {
          function_name: "search_web",
          display_name: "Web Search",
          description: "Searches the web",
        },
        t
      )
    ).toBe("Searches the web")
  })

  test("localizes built-in tool sources", () => {
    expect(
      toolSourceDisplayName({ kind: "builtin", name: "Builtin" }, t)
    ).toBe("内置")
  })

  test("falls back to the source name for external sources", () => {
    expect(
      toolSourceDisplayName({ kind: "mcp", name: "Search MCP" }, t)
    ).toBe("Search MCP")
  })

  test("normalizes absolute artifact URLs and keeps the latest file version", () => {
    const oldUrl = "/api/v1/artifacts/old-token"
    const latestUrl = "/api/v1/artifacts/latest-token"
    const value = withArtifactDownloadLinks(
      `下载：https://chat.kimi.com${latestUrl}`,
      [
        {
          tool_name: "create_artifact",
          status: "succeeded",
          output: { filename: "论文.docx", download_url: oldUrl },
        },
        {
          tool_name: "create_artifact",
          status: "succeeded",
          output: { filename: "论文.docx", download_url: latestUrl },
        },
      ]
    )

    expect(value).toBe(`下载：[论文.docx](${latestUrl})`)
    expect(value).not.toContain("chat.kimi.com")
    expect(value).not.toContain(oldUrl)
  })

  test("links artifacts returned by built-in Skill tools", () => {
    const url = "/api/v1/artifacts/pptx-token"
    const value = withArtifactDownloadLinks("文件已生成：review.pptx", [
      {
        tool_name: "pptx_skill",
        status: "succeeded",
        output: { filename: "review.pptx", download_url: url },
      },
    ])

    expect(value).toContain(`[review.pptx](${url})`)
  })

  test("shows a generated image preview and its downloadable filename", () => {
    const url = "/api/v1/artifacts/83ccbf9c-7c17-4d78-a46d-637bb88ef48e"
    const signedUrl = "/api/v1/artifacts/eyJhbGciOiJIUzI1NiJ9.signed"
    const value = withArtifactDownloadLinks(
      [
        "画好了。",
        "- 文件名：`generated-image-a1b2.png`",
        `- 预览链接：[点击预览](${signedUrl}/preview)`,
        `- 下载链接：[generated-image-a1b2.png](${signedUrl})`,
      ].join("\n"),
      [
        {
          tool_name: "generate_image",
          status: "succeeded",
          output: {
            artifact_id: "83ccbf9c-7c17-4d78-a46d-637bb88ef48e",
            filename: "generated-image-a1b2.png",
            download_url: signedUrl,
            preview_url: `${signedUrl}/preview`,
          },
        },
      ]
    )
    expect(value).toContain(`![generated-image.png](${url}/preview)`)
    expect(value).toContain(`[generated-image.png](${url})`)
    expect(value).not.toContain("generated-image-a1b2.png")
    expect(value).not.toContain("预览链接")
    expect(value).not.toContain("点击预览")
    expect(value).not.toContain(signedUrl)
  })

  test("keeps an image already embedded by the agent without duplicating or rewriting it", () => {
    const url = "/api/v1/artifacts/83ccbf9c-7c17-4d78-a46d-637bb88ef48e"
    const value = withArtifactDownloadLinks(
      `- 预览链接：点击预览\n\n![生成图片](${url}/preview)`,
      [
        {
          tool_name: "generate_image",
          status: "succeeded",
          output: {
            artifact_id: "83ccbf9c-7c17-4d78-a46d-637bb88ef48e",
            filename: "generated.png",
            download_url: url,
            preview_url: `${url}/preview`,
          },
        },
      ]
    )

    expect(value).not.toContain("预览链接")
    expect(value).toContain(`![生成图片](${url}/preview)`)
    expect(value).toContain(`[generated-image.png](${url})`)
    expect(value.match(/\/preview/g)).toHaveLength(1)
  })

  test("keeps multiple generated images that share the friendly filename", () => {
    const firstId = "83ccbf9c-7c17-4d78-a46d-637bb88ef48e"
    const secondId = "9f71a7fe-2752-4ee2-8c63-d1fc8780e7bd"
    const events = [firstId, secondId].map((artifactId) => ({
      tool_name: "generate_image",
      status: "succeeded",
      output: {
        artifact_id: artifactId,
        filename: "generated-image.png",
        download_url: `/api/v1/artifacts/${artifactId}`,
        preview_url: `/api/v1/artifacts/${artifactId}/preview`,
      },
    }))

    const value = withArtifactDownloadLinks("两张图片都生成好了。", events)

    expect(value).toContain(
      `[generated-image.png](/api/v1/artifacts/${firstId})`
    )
    expect(value).toContain(
      `[generated-image.png](/api/v1/artifacts/${secondId})`
    )
    expect(value.match(/!\[generated-image\.png\]/g)).toHaveLength(2)
  })

  test("leaves a preview URL untouched without a verified tool event", () => {
    const previewUrl =
      "/api/v1/artifacts/d027f57a-d1e2-411e-9aef-692362dfe8ba/preview"
    const content = `- 预览：${previewUrl}`

    const value = withArtifactDownloadLinks(content, [])

    expect(value).toBe(content)
  })

  test("does not duplicate a bare UUID image preview when its tool event is present", () => {
    const artifactId = "d027f57a-d1e2-411e-9aef-692362dfe8ba"
    const downloadUrl = `/api/v1/artifacts/${artifactId}`
    const previewUrl = `${downloadUrl}/preview`
    const value = withArtifactDownloadLinks(`- 预览：${previewUrl}`, [
      {
        tool_name: "generate_image",
        status: "succeeded",
        output: {
          artifact_id: artifactId,
          filename: "generated-image.png",
          download_url: downloadUrl,
          preview_url: previewUrl,
        },
      },
    ])

    expect(value.match(/!\[generated-image\.png\]/g)).toHaveLength(1)
    expect(value).not.toContain(`预览：${previewUrl}`)
    expect(value).toContain(`[generated-image.png](${downloadUrl})`)
  })

  test("embeds a UUID preview written as a Markdown link in the answer", () => {
    const artifactId = "d027f57a-d1e2-411e-9aef-692362dfe8ba"
    const downloadUrl = `/api/v1/artifacts/${artifactId}`
    const previewUrl =
      "/api/v1/artifacts/d027f57a-d1e2-411e-9aef-692362dfe8ba/preview"
    const content = `- 预览：[${previewUrl}](${previewUrl})`

    const value = withArtifactDownloadLinks(content, [
      {
        tool_name: "generate_image",
        status: "succeeded",
        output: {
          artifact_id: artifactId,
          filename: "generated-image.png",
          download_url: downloadUrl,
          preview_url: previewUrl,
        },
      },
    ])

    expect(value).toContain(`![generated-image.png](${previewUrl})`)
    expect(value).not.toContain(`预览：[${previewUrl}]`)
  })

  test("does not turn arbitrary preview links into images", () => {
    const content =
      "- 预览：https://example.com/image.png\n- 预览：/api/v1/artifacts/not-a-uuid/preview"
    expect(withArtifactDownloadLinks(content, [])).toBe(content)
  })

  test("replaces a copied artifact token with the verified filename link", () => {
    const validUrl = "/api/v1/artifacts/valid-token"
    const copiedUrl = "/api/v1/artifacts/copied-token"
    const value = withArtifactDownloadLinks(
      `下载链接：[${copiedUrl}](${copiedUrl})`,
      [
        {
          tool_name: "create_artifact",
          status: "succeeded",
          output: { filename: "verify_stream.py", download_url: validUrl },
        },
      ]
    )

    expect(value).toBe(`下载链接：[verify_stream.py](${validUrl})`)
    expect(value).not.toContain(copiedUrl)
  })

  test("normalizes raw artifact URLs in log content", () => {
    const url = "/api/v1/artifacts/production-token"
    const value = withArtifactDownloadLinksInContent(
      `文件名：校外培训行政处罚相关条例汇编.docx\n下载链接：${url}`
    )

    expect(value).toContain(`[校外培训行政处罚相关条例汇编.docx](${url})`)
    expect(value).not.toContain(`下载链接：${url}`)
  })

  test("normalizes links split by whitespace and ignores unmentioned artifacts", () => {
    const url = "/api/v1/artifacts/document-token"
    const tempUrl = "/api/v1/artifacts/test-token"
    const value = withArtifactDownloadLinks(
      `文件名：规章制度（通用模板）.docx\n下载：[规章制度（通用模板）.docx]\n(${url})`,
      [
        {
          tool_name: "create_artifact",
          status: "succeeded",
          output: { filename: "规章制度（通用模板）.docx", download_url: url },
        },
        {
          tool_name: "create_artifact",
          status: "succeeded",
          output: { filename: "test_docx.py", download_url: tempUrl },
        },
      ]
    )

    expect(value).toContain(`[规章制度（通用模板）.docx](${url})`)
    expect(value).not.toContain(tempUrl)
    expect(value).not.toContain("test_docx.py")
  })
})
