import { type TranslationKey } from "@/i18n"

export const DEFAULT_USER_PASSWORD = "NexaFlow@123"

export const STATUS_LABEL_KEYS: Record<string, TranslationKey> = {
  active: "已启用",
  archived: "已归档",
  disabled: "已停用",
}
export const AUDIT_DETAIL_LABEL_KEYS: Record<string, TranslationKey> = {
  email: "邮箱",
  is_active: "启用状态",
  is_global_admin: "全局管理员",
  name: "名称",
  description: "描述",
  slug: "标识",
  status: "状态",
  team_ids: "团队 ID",
  username: "用户名",
  workspace_id: "工作空间 ID",
  knowledge_base_id: "知识库 ID",
  document_id: "文档 ID",
  task_id: "任务 ID",
  user_id: "用户 ID",
  chunk_count: "分片数",
  document_count: "文档数",
  size_bytes: "大小",
  permission: "权限",
}
export const AUDIT_ACTION_LABEL_KEYS: Record<string, TranslationKey> = {
  "workspace.create": "新建工作空间",
  "workspace.update": "更新工作空间",
  "workspace.archive": "归档工作空间",
  "workspace.restore": "恢复工作空间",
  "workspace.delete": "删除工作空间",
  "team.create": "新建团队",
  "team.update": "更新团队",
  "team.archive": "归档团队",
  "team.restore": "恢复团队",
  "team.delete": "删除团队",
  "user.create": "新建用户",
  "user.update": "更新用户",
  "user.reset_password": "修改密码",
  "user.change_password": "修改密码",
  "user.deactivate": "停用用户",
  "user.delete": "删除用户",
  "model.create": "接入模型",
  "model.update": "更新模型",
  "model.delete": "删除模型",
  "workspace.member.add": "添加成员",
  "workspace.member.remove": "移除成员",
  "workspace.member.update": "更新成员角色",
  "knowledge_base.create": "新建知识库",
  "knowledge_base.update": "更新知识库",
  "knowledge_base.delete": "删除知识库",
  "knowledge_document.upload": "上传文档",
  "knowledge_document.parse": "解析文档",
  "knowledge_document.index": "向量化文档",
  "knowledge_document.delete": "删除文档",
  "knowledge_document.activate": "启用文档",
  "knowledge_document.deactivate": "停用文档",
  "knowledge_document.batch_create": "批量导入文档",
  "knowledge_task.retry": "重试任务",
  "knowledge_task.parse.queue": "解析任务排队",
  "knowledge_task.parse.succeed": "解析任务完成",
  "knowledge_task.parse.fail": "解析任务失败",
  "knowledge_task.index.fail": "向量化任务失败",
  "knowledge_task.rebuild_index.fail": "重建索引失败",
  "resource_permission.grant": "授权资源",
  "resource_permission.revoke": "撤销授权",
}
